telegram:
  bot:
    name: InventoryManagement777Bot
    token: 6865322504:AAEn1eIIvRwjc8HxWB2N-4bK-p08mLTVXMk
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8082
