telegram:
  bot:
    name: InventoryManagement777Bot
    token: ${TELEGRAM_TOKEN}
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: somepostgres
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8082
